apiVersion: v1
kind: Service
metadata:
  name: steam-headless-web
  namespace: steam-headless
spec:
  type: LoadBalancer
  selector:
    app: steam-headless
  ports:
    - name: novnc
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: sunshine-ui
      protocol: TCP
      port: 47990
      targetPort: 47990
    - name: sun-ctrl
      protocol: TCP
      port: 47989
      targetPort: 47989
    - name: sun-stream
      protocol: TCP
      port: 48010
      targetPort: 48010
